### ISSUE TITLE
No transaction history saved.

### ISSUE THREAD

**Issue by jpstokes** [2018kguo/RobinhoodBot#12]
Ran bot but after purchasing stock no transaction history saved.

**Comment by 2018kguo** [comment]
my apologies, this piece of functionality is something that I somewhat overlooked because I didn't feel like it was very important and ended up implementing in a misleading way - the "tradehistory" file doesn't log every purchase you make, but instead logs the results of how much profit/loss was incurred when the bot decides to sell a stock. For example, if the bot buys a share of APL on Monday and then sells it on Friday, it will only write to the file upon selling the stock - saying you made/lost $X. If the bot buys APL and then holds on to it, nothing is logged because in the bot's mind, you haven't gained or lost any actual money until you decide to sell it. I do think that it is better to log every transaction though. I'll try to remedy this at some point.

**Comment by jpstokes** [comment]
Your explanation is good enough for me. So if I understand, the bot will calculate the profit/loss based on buy/sold info that it gets from Robinhood so it doesn't need to save data at time of purchase? If that's the case, I can live with that.
