### ISSUE TITLE
Login issue?

### ISSUE THREAD

**Issue by shevzor** [2018kguo/RobinhoodBot#16]
Hi,
The bot seems to log in, however it never asks me to enter the auth code from my email... and then it never buys or sells anything.

----- Starting scan... -----

Current Portfolio: ['GE']

Current Watchlist: ['AAL', 'OXY', 'EXPE', 'TSLA', 'NFLX', 'MSFT', 'SBUX', 'BABA', 'BAC', 'GE', 'OGZPY', 'MZDAY']

----- Scanning portfolio for stocks to sell -----

----- Scanning watchlist for stocks to buy -----

----- Scan over -----

>>> 

Always just runs like this... doesn't take any actions.

**Comment by 2018kguo** [comment]
It's working, it's just that none of the stocks on your watchlist happened to meet the requirements to buy/sell. You can probably get it to trigger a buy/sell by using exponential moving averages instead, try replacing lines 177-178 in main.py with ta.trend.EMAIndicator instead of ta.volatility.bollinger_mavg.

**Comment by shevzor** [comment]
Thank you, however something is not right, the watchlist doesnt match what I have in there. I removed the old one and created a new one. with totally different stocks in there and it still shows the old list. It was over 24 hours ago that I have replaced them. 

The current PORTFOLIO updates properly.

**Comment by shevzor** [comment]
Also, Ive tried to change my password(put a wrong password) and it gave me exactly the same results... meaning that something is not working right with the login.
